### ISSUE TITLE
Fix bugs builds

### ISSUE THREAD

**Issue by felipemarts** [DevelBlockchain/bywise#49]
From `devel` branch run `npm run build`
It will return some refactoring errors.

In the old implementation:
`new Wallet(seed:"string_seed_phrase");`

Refactor to:
`new Wallet("string_seed_phrase");`

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

I have already made a contribution to the open-source ecosystem and am excited to continue learning and collaborating on innovative projects

### How I plan on tackling this issue
If I need to refactor the Wallet code to accept just a string instead of an object with a seed property, I'd start by updating the constructor to take the seed phrase directly as an argument. Then, I'd go through the code to update where the old constructor was used. After that, I'd run the build to check for any remaining errors and fix them if needed.

**Comment by 0xJeanmi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
I'm full stack developer with experience in languages like PHP, JS, TS and Frameworks like React, Laravel. Also, I made several courses in Alchemy University to be prepared to challenges in web3 like this one. So I hope to move forward in this application.

### How I plan on tackling this issue
Well, run npm run build, see the errors and then fix them with new implementations as shown in the latest version of the documentation.

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
With over four years of experience in blockchain development, I have worked across multiple blockchain ecosystems. My expertise spans the entire development lifecycle—from project conceptualization and smart contract design to managing on-chain interactions, seamless protocol integration, and implementing strong security practices.

This enables me to handle both on-chain and off-chain infrastructure, ensuring the development of reliable, scalable blockchain applications.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
3+ years Full Stack developer

### How I plan on tackling this issue
I will refactor all instances of new Wallet(seed: "string_seed_phrase") to new Wallet("string_seed_phrase") and update the Wallet class constructor to accept a string argument. Then, I will run npm run build to ensure the issue is resolved.

**Comment by satoshidisciple** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
This demand is super simple, I can start with it.
